const SUPERMARKET_DELIVERY_PERMISSIONS = {
  SELF_ONLY: 'self_only',
  RIDER_ONLY: 'rider_only',
  HYBRID: 'hybrid'
};

const SUPERMARKET_DELIVERY_MODES = {
  PENDING: 'pending',
  SELF_DELIVERY: 'self_delivery',
  RIDER_DELIVERY: 'rider_delivery'
};

const SUPERMARKET_SETTLEMENT_RULES = {
  DEFAULT: 'default_takeout',
  HYBRID_PENDING: 'supermarket_hybrid_pending',
  SELF_DELIVERY_FIXED: 'supermarket_self_delivery_fixed_3',
  RIDER_DELIVERY_FIXED: 'supermarket_rider_delivery_fixed_1'
};

const PERMISSION_ALIASES = {
  [SUPERMARKET_DELIVERY_PERMISSIONS.SELF_ONLY]: SUPERMARKET_DELIVERY_PERMISSIONS.SELF_ONLY,
  self: SUPERMARKET_DELIVERY_PERMISSIONS.SELF_ONLY,
  selfonly: SUPERMARKET_DELIVERY_PERMISSIONS.SELF_ONLY,
  self_delivery: SUPERMARKET_DELIVERY_PERMISSIONS.SELF_ONLY,
  merchant_self: SUPERMARKET_DELIVERY_PERMISSIONS.SELF_ONLY,
  '自己配送': SUPERMARKET_DELIVERY_PERMISSIONS.SELF_ONLY,
  '老板配送': SUPERMARKET_DELIVERY_PERMISSIONS.SELF_ONLY,
  '商家自配': SUPERMARKET_DELIVERY_PERMISSIONS.SELF_ONLY,
  '自配送': SUPERMARKET_DELIVERY_PERMISSIONS.SELF_ONLY,
  '自己配': SUPERMARKET_DELIVERY_PERMISSIONS.SELF_ONLY,

  [SUPERMARKET_DELIVERY_PERMISSIONS.RIDER_ONLY]: SUPERMARKET_DELIVERY_PERMISSIONS.RIDER_ONLY,
  rider: SUPERMARKET_DELIVERY_PERMISSIONS.RIDER_ONLY,
  rideronly: SUPERMARKET_DELIVERY_PERMISSIONS.RIDER_ONLY,
  rider_delivery: SUPERMARKET_DELIVERY_PERMISSIONS.RIDER_ONLY,
  station_delivery: SUPERMARKET_DELIVERY_PERMISSIONS.RIDER_ONLY,
  '骑手配送': SUPERMARKET_DELIVERY_PERMISSIONS.RIDER_ONLY,
  '骑手派送': SUPERMARKET_DELIVERY_PERMISSIONS.RIDER_ONLY,
  '站长配送': SUPERMARKET_DELIVERY_PERMISSIONS.RIDER_ONLY,
  '站长派送': SUPERMARKET_DELIVERY_PERMISSIONS.RIDER_ONLY,

  [SUPERMARKET_DELIVERY_PERMISSIONS.HYBRID]: SUPERMARKET_DELIVERY_PERMISSIONS.HYBRID,
  both: SUPERMARKET_DELIVERY_PERMISSIONS.HYBRID,
  hybrid: SUPERMARKET_DELIVERY_PERMISSIONS.HYBRID,
  self_and_rider: SUPERMARKET_DELIVERY_PERMISSIONS.HYBRID,
  self_or_rider: SUPERMARKET_DELIVERY_PERMISSIONS.HYBRID,
  '两个都选': SUPERMARKET_DELIVERY_PERMISSIONS.HYBRID,
  '2个都选': SUPERMARKET_DELIVERY_PERMISSIONS.HYBRID,
  '两者都支持': SUPERMARKET_DELIVERY_PERMISSIONS.HYBRID,
  '都支持': SUPERMARKET_DELIVERY_PERMISSIONS.HYBRID,
  '自己配送和骑手配送': SUPERMARKET_DELIVERY_PERMISSIONS.HYBRID,
  '自己配送/骑手配送': SUPERMARKET_DELIVERY_PERMISSIONS.HYBRID
};

const MODE_ALIASES = {
  [SUPERMARKET_DELIVERY_MODES.PENDING]: SUPERMARKET_DELIVERY_MODES.PENDING,
  pending: SUPERMARKET_DELIVERY_MODES.PENDING,

  [SUPERMARKET_DELIVERY_MODES.SELF_DELIVERY]: SUPERMARKET_DELIVERY_MODES.SELF_DELIVERY,
  self: SUPERMARKET_DELIVERY_MODES.SELF_DELIVERY,
  self_delivery: SUPERMARKET_DELIVERY_MODES.SELF_DELIVERY,
  merchant_self: SUPERMARKET_DELIVERY_MODES.SELF_DELIVERY,
  '自己配送': SUPERMARKET_DELIVERY_MODES.SELF_DELIVERY,
  '老板配送': SUPERMARKET_DELIVERY_MODES.SELF_DELIVERY,
  '商家自配': SUPERMARKET_DELIVERY_MODES.SELF_DELIVERY,

  [SUPERMARKET_DELIVERY_MODES.RIDER_DELIVERY]: SUPERMARKET_DELIVERY_MODES.RIDER_DELIVERY,
  rider: SUPERMARKET_DELIVERY_MODES.RIDER_DELIVERY,
  rider_delivery: SUPERMARKET_DELIVERY_MODES.RIDER_DELIVERY,
  station_delivery: SUPERMARKET_DELIVERY_MODES.RIDER_DELIVERY,
  '骑手配送': SUPERMARKET_DELIVERY_MODES.RIDER_DELIVERY,
  '站长配送': SUPERMARKET_DELIVERY_MODES.RIDER_DELIVERY,
  '骑手派送': SUPERMARKET_DELIVERY_MODES.RIDER_DELIVERY
};

const normalizeTextKey = (value) => String(value || '').trim().toLowerCase().replace(/\s+/g, '_');

const normalizeSupermarketDeliveryPermission = (value) => {
  if (value === undefined || value === null || value === '') {
    return null;
  }
  return PERMISSION_ALIASES[normalizeTextKey(value)] || PERMISSION_ALIASES[String(value).trim()] || null;
};

const normalizeSupermarketDeliveryMode = (value) => {
  if (value === undefined || value === null || value === '') {
    return null;
  }
  return MODE_ALIASES[normalizeTextKey(value)] || MODE_ALIASES[String(value).trim()] || null;
};

const resolveInitialSupermarketDeliveryMode = (permission) => {
  switch (permission) {
    case SUPERMARKET_DELIVERY_PERMISSIONS.SELF_ONLY:
      return SUPERMARKET_DELIVERY_MODES.SELF_DELIVERY;
    case SUPERMARKET_DELIVERY_PERMISSIONS.RIDER_ONLY:
      return SUPERMARKET_DELIVERY_MODES.RIDER_DELIVERY;
    case SUPERMARKET_DELIVERY_PERMISSIONS.HYBRID:
      return SUPERMARKET_DELIVERY_MODES.PENDING;
    default:
      return null;
  }
};

module.exports = {
  SUPERMARKET_DELIVERY_PERMISSIONS,
  SUPERMARKET_DELIVERY_MODES,
  SUPERMARKET_SETTLEMENT_RULES,
  normalizeSupermarketDeliveryPermission,
  normalizeSupermarketDeliveryMode,
  resolveInitialSupermarketDeliveryMode
};
